### ISSUE TITLE
Incomplete installation on Mac OS 10.9.5?

### ISSUE THREAD

**Issue by jkleiser** [sotownsend/BooJS#4]
I did this:
sudo gem install boojs
- and after I entered my password, I got this:

Fetching: phantomjs-1.9.8.0.gem (100%)
Successfully installed phantomjs-1.9.8.0
Fetching: greenletters-0.3.0.gem (100%)
Successfully installed greenletters-0.3.0
Fetching: boojs-0.0.16.gem (100%)
Successfully installed boojs-0.0.16
Parsing documentation for phantomjs-1.9.8.0
Installing ri documentation for phantomjs-1.9.8.0
Parsing documentation for greenletters-0.3.0
Installing ri documentation for greenletters-0.3.0
Parsing documentation for boojs-0.0.16
Installing ri documentation for boojs-0.0.16
3 gems installed

The I tried this:
boojs
- and I got this:

Phantomjs does not appear to be installed in /Users/myname/.phantomjs/1.9.8/darwin/bin/phantomjs, installing!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
100 9187k  100 9187k    0     0   838k      0  0:00:10  0:00:10 --:--:-- 1979k
Archive:  phantomjs-1.9.8-macosx.zip
- and some creating/inflating, and at the end this:

Successfully installed phantomjs. Yay!
Removed temporarily downloaded files.
- and that's all, no prompt. I did Ctrl-C and boojs again, but no prompt.
  I then removed an old phantomjs 1.9.1, and made sure that the 1.9.8 was now in my PATH, but I still get no prompt from books, and no reactions when I try some commands.

**Comment by seosgithub** [comment]
You may also want to try an update, there have been many improvements over the past 24 hours.

`gem uninstall boojs`
`gem install boojs``

Also, could you execute these two commands and paste them into here, that would help diagnosing the issue as this could be many possible problems:
1. `ruby -v`
2. `gem env`

**Comment by jkleiser** [comment]
Sorry, I see that my Ruby is to old:

$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]

$ gem env
RubyGems Environment:
- RUBYGEMS VERSION: 2.0.14
- RUBY VERSION: 2.0.0 (2014-05-08 patchlevel 481) [universal.x86_64-darwin13]
- INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
- RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
- EXECUTABLE DIRECTORY: /usr/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - universal-darwin-13
- GEM PATHS:
  - /Library/Ruby/Gems/2.0.0
  - /Users/myname/.gem/ruby/2.0.0
  - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/

I'll consider upgrading my Ruby.

**Comment by seosgithub** [comment]
Have you tried https://rvm.io?  You just run `\curl -sSL https://get.rvm.io | bash -s stable` in your terminal and follow the directions.  When it's done, re-open your terminal and run `rvm install 2.1.0` and `rvm --default use 2.1.0`  The native ruby environment that comes preinstalled with Mac OS X is broken; rvm has become the defacto community standard.
