### ISSUE TITLE
Logo needs dithering

### ISSUE THREAD

**Issue by CoolOppo** [sotownsend/BooJS#7]
The logo has some pretty bad banding artifacts which could be easily negated using dithering when quantizing the gradients down to an 8-bit PNG (which is what I'm assuming you're doing because otherwise you wouldn't need to quantize the colors to even cause banding in the first place).

**Comment by seosgithub** [comment]
You don't like the retro feel?  :tongue: I am willing to integrate a pull request with the fixes you recomendedd if you submit one.  Thank you for the suggestions.  If you're unsure how to submit a pull request:
1. Fork this project
2. Make your changes to your own project (your project would then be **CoolOppo/BooJS**
3. Come back to this project and click **pull request** on the right side
4. Click **Create pull request**, select **CoolOppo/BooJS** as the **Head**

**Comment by CoolOppo** [comment]
I would have done it if I had the original source for the logo. In order to do it with the current one, I would either need to apply some sort of filter that uses a heuristic (almost always bad results) or remake it myself.

Edit: or some combination of the two.

**Comment by seosgithub** [comment]
Attached is the PSD.  Please feel free to do what you want with it; I'm sure you'll do a better job than I was able to do.

#The PSD
https://www.dropbox.com/s/46pjj7smpu16cdg/boojs.psd.zip?dl=0

#Original inspiration
![maxresdefault](https://cloud.githubusercontent.com/assets/1043162/7264981/df079464-e860-11e4-8d76-bce22f01e674.jpg)

**Comment by CoolOppo** [comment]
Huh. The PSD is not the same color as [the current rendered logo](https://raw.githubusercontent.com/sotownsend/BooJS/f8b79a6802ff1809c6d29a7b9252349db2653cd6/logo.png) (linked for future reference).

Either way, here's the result of [fixing the coloring](https://visionless.me/u/iupOl-1429674701.589.png) of the PSD:
![boojs](https://cloud.githubusercontent.com/assets/1498177/7266893/a89ee57a-e87f-11e4-991d-eea826d178e0.png)

If, for some atrocious reason, you need an 8-bit PNG to save 8 _enormous_ kilobytes (sarcasm) [here is the mutilated version](https://cloud.githubusercontent.com/assets/1498177/7266966/0b5a8236-e881-11e4-9cd8-d56e4d04edba.png).

**Comment by seosgithub** [comment]
Looks great!  Can you create a pull request for this?  I can publish it myself, but you will get no credit.

**Comment by CoolOppo** [comment]
You can go right ahead and publish it; I only re-rendered it!
