### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by arrayest** [sotownsend/BooJS#8]
I want to use [Sourcegraph](https://sourcegraph.com) for BooJS code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/sotownsend/BooJS. (It should only take 30 seconds.)

Thank you!

**Comment by seosgithub** [comment]
I am having trouble trusting this website. Do you have any links that back up it's validity?
